apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-script
data:
  backup.sh: |
    #!/bin/bash
    set -ex
    apt update
    apt install wget
    apt install default-mysql-client -y
    sleep 5
    cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
    echo "Asia/Kolkata" > /etc/timezone
    backup_filename="mariadbbackup_"$(date +"%d.%m.%y-%H-%M-%S")
    echo -e "\nBacking Up ..."
    mysqldump -h ${DB_HOST} -P ${DB_PORT} -u ${DB_ADMIN_USER} -p ${DBPASSWORD} -A --opt --column-statistics=0  > ${backup_filename}
    if [[ $? != 0 ]]
    then
        echo "Exiting......"
        exit
    fi
    sleep 10
    echo -e "\nFinished Backup"
    tar -czf ${backup_filename}".tar.gz" ${backup_filename}
    gcloud config set project ${GCLOUD_PROJECT}
    if [[ ! -z $GOOGLE_APPLICATION_CREDENTIALS ]]
    then
        gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
    fi
    gsutil cp ${backup_filename}".tar.gz" gs://${BUCKET_NAME}
    sleep 10
    if [[ ! -z $GOOGLE_APPLICATION_CREDENTIALS ]]
    then
    gcloud auth revoke
    fi